language: python

python: 
    - "3.6"
    - "3.7"
    - "3.8"

install:
    - pip install -r requirements-test.txt
    - pip install coveralls

script:
    - make test

after_success:
    - coveralls
